apiVersion: apps/v1
kind: Deployment
metadata:
  name: gibbersound-backend
  namespace: gibbersound
  labels:
    app: gibbersound
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gibbersound
      tier: backend
  template:
    metadata:
      labels:
        app: gibbersound
        tier: backend
    spec:
      containers:
      - name: gibbersound-backend
        image: fpinero/gibbersound-backend:0.2.8
        imagePullPolicy: Always
        ports:
        - containerPort: 5001
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
        env:
        - name: FLASK_ENV
          value: "production"
        - name: DEEPSEEK_API_KEY
          valueFrom:
            secretKeyRef:
              name: deepseek-api-credentials
              key: DEEPSEEK_API_KEY
        livenessProbe:
          httpGet:
            path: /api/health
            port: 5001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 5001
          initialDelaySeconds: 5
          periodSeconds: 5
      nodeSelector:
        kubernetes.io/arch: arm64 