apiVersion: v1
kind: Service
metadata:
  name: gibbersound-backend
  namespace: gibbersound
  labels:
    app: gibbersound
    tier: backend
spec:
  selector:
    app: gibbersound
    tier: backend
  ports:
  - port: 5001
    targetPort: 5001
  type: ClusterIP 