FROM nginx:alpine

# Configuración para arquitectura ARM
ARG TARGETPLATFORM
ARG BUILDPLATFORM
RUN echo "Building on $BUILDPLATFORM for $TARGETPLATFORM"

# Copiar solo archivos estáticos (no las plantillas)
COPY static /usr/share/nginx/html/static

# Configuración de Nginx
COPY k8s/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"] 