FROM nginx:alpine

# Configuración para arquitectura ARM
ARG TARGETPLATFORM
ARG BUILDPLATFORM
RUN echo "Building on $BUILDPLATFORM for $TARGETPLATFORM"

# Copiar archivos estáticos
COPY static /usr/share/nginx/html/static
COPY templates /usr/share/nginx/html/templates

# Configuración de Nginx
COPY k8s/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"] 