FROM python:3.12-slim

# Configuración para arquitectura ARM
ARG TARGETPLATFORM
ARG BUILDPLATFORM
RUN echo "Building on $BUILDPLATFORM for $TARGETPLATFORM"

WORKDIR /app

# Instalar dependencias
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copiar el código de la aplicación
COPY . .

# Exponer el puerto que usa Flask
EXPOSE 5000

# Comando para iniciar la aplicación
CMD ["python", "app.py"] 