apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-nginx-config
  namespace: gibbersound
data:
  default.conf: |
    server {
        listen 80;
        server_name localhost;

        # Servir archivos estáticos directamente
        location /static/ {
            alias /usr/share/nginx/html/static/;
            expires 30d;
            add_header Cache-Control "public, max-age=2592000";
            try_files $uri $uri/ =404;
        }

        # Servir los reportes de estadísticas
        location /stats/ {
            alias /var/log/nginx/stats/;
            autoindex on;
            expires off;
            add_header Cache-Control "no-store, must-revalidate";
            try_files $uri $uri/ =404;
        }

        # Servir favicon.ico directamente
        location = /favicon.ico {
            alias /usr/share/nginx/html/static/favicon/favicon.ico;
            expires 30d;
            add_header Cache-Control "public, max-age=2592000";
        }

        # Redirigir peticiones API al backend
        location /api/ {
            proxy_pass http://gibbersound-backend:5001;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_connect_timeout 60s;
            proxy_send_timeout 60s;
            proxy_read_timeout 60s;
            
            # Configuración CORS explícita
            add_header 'Access-Control-Allow-Origin' '*' always;
            add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS' always;
            add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization,Origin,Accept' always;
            add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range' always;
            add_header 'Access-Control-Allow-Credentials' 'true' always;
            
            # Manejar solicitudes OPTIONS
            if ($request_method = 'OPTIONS') {
                add_header 'Access-Control-Allow-Origin' '*';
                add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
                add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization,Origin,Accept';
                add_header 'Access-Control-Max-Age' 1728000;
                add_header 'Content-Type' 'text/plain; charset=utf-8';
                add_header 'Content-Length' 0;
                return 204;
            }
        }

        # Servir el contenido estático para la ruta principal
        location / {
            root /usr/share/nginx/html;
            index index.html;
            try_files $uri $uri/ /index.html;
        }
    } 