apiVersion: apps/v1
kind: Deployment
metadata:
  name: gibbersound-frontend
  namespace: gibbersound
  labels:
    app: gibbersound
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gibbersound
      tier: frontend
  template:
    metadata:
      labels:
        app: gibbersound
        tier: frontend
    spec:
      initContainers:
      - name: init-chmod-logs
        image: busybox
        command: ['sh', '-c', 'mkdir -p /var/log/nginx/stats && chmod -R 755 /var/log/nginx']
        volumeMounts:
        - name: nginx-logs
          mountPath: /var/log/nginx
      containers:
      - name: frontend
        image: fpinero/gibbersound-frontend:0.2.8
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "300m"
            memory: "256Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
        livenessProbe:
          httpGet:
            path: /static/favicon/favicon.ico
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 20
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /static/favicon/favicon.ico
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
        volumeMounts:
        - name: nginx-logs
          mountPath: /var/log/nginx
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
      volumes:
      - name: nginx-logs
        persistentVolumeClaim:
          claimName: nginx-logs-pvc
      - name: nginx-config
        configMap:
          name: nginx-config
          items:
          - key: default.conf
            path: default.conf
      nodeSelector:
        kubernetes.io/arch: arm64 