apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: gibbersound
data:
  default.conf: |
    # Definir el formato de log en el contexto http
    log_format custom_log '$remote_addr - $remote_user [$time_local] '
                        '"$request" $status $body_bytes_sent '
                        '"$http_referer" "$http_user_agent" '
                        '$request_time $upstream_response_time '
                        '$upstream_addr';

    server {
        listen 80;
        server_name localhost;

        # Logs de acceso
        access_log /var/log/nginx/access.log custom_log;
        
        # Logs de error
        error_log /var/log/nginx/error.log;

        location / {
            root /usr/share/nginx/html;
            index index.html;
            try_files $uri $uri/ /index.html;
        }

        # Servir directorio de estadísticas desde los logs
        location /stats/ {
            alias /var/log/nginx/stats/;
            autoindex off;
            # Configuración para navegadores
            add_header Cache-Control "no-cache, no-store, must-revalidate";
            add_header Pragma "no-cache";
            add_header Expires "0";
            # Para HTML
            types {
                text/html html htm;
            }
            # Permitir todos los orígenes para facilitar la integración
            add_header 'Access-Control-Allow-Origin' '*';
        }

        # Configuración de seguridad básica
        add_header X-Frame-Options "SAMEORIGIN";
        add_header X-XSS-Protection "1; mode=block";
        add_header X-Content-Type-Options "nosniff";
    } 